import Head from 'next/head'
import { useAuth } from "../hooks/auth";
import { Button } from "@chakra-ui/react";

export default function Home() {
  const auth = useAuth();

  if (auth.user) {
    return (
      <>
        Signed In!
        <Button onClick={auth.signout}>Sign Out</Button>
      </>
    );
  }else{
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Button onClick={auth.signin}>Sign In</Button>
        </main>
      </div>
    );
  }
}
